### PR TITLE
Add "craptev1-v1.1.tar.xz" and "crapto1-v3.3.tar.xz" to the repository.

### PR DESCRIPTION
**Pull request by DavidBerdik**
The download links for the `craptev1-v1.1.tar.xz` and `crapto1-v3.3.tar.xz` packages in the README are broken, but I was able to find them elsewhere online. To simplify usage a bit, they should be added to the repository.

### CODE REVIEW

**Comment by LudovicRousseau** [comment]
I don't think it is a good idea to to add binary `.tar.xz` files to a git repository.
Why not add the _content_ of the archive instead?

**Comment by doegox** [comment]
@DavidBerdik Did you read the license of craptev1?

> No redistribution. No modifications.

That's why they're not in this repo

**Comment by DavidBerdik** [comment]
@doegox Ah, okay. My bad. I did not read the license of it because I was not able to find it, but I assumed that redistribution was allowed.

**Comment by doegox** [comment]
it's written in the header of the source code

**Comment by DavidBerdik** [comment]
Maybe so, but I never looked at it. It is unfortunate that the original developers chose to make it so restrictive and then stopped sharing it themselves, but I understand the implications of the license.

**Comment by doegox** [comment]
indeed, weird and unfortunate

**Comment by DavidBerdik** [comment]
At the very least, could the README be updated with the working download links I have? A hash of the files should also probably be listed for safety.

**Comment by doegox** [comment]
ok please submit a PR

**Comment by DavidBerdik** [comment]
Done! - #14

**Pull request closed without merging**
